'use server';

import PDFDocument from 'pdfkit';

export async function extractTextFromFile(file: File): Promise<string> {
    console.log(`[GAP_UTILS] Extracting text from ${file.name} (${file.type})...`);
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    if (file.type === 'application/pdf') {
        try {
            const pdf = require('pdf-parse');
            const data = await pdf(buffer);
            return data.text;
        } catch (err: any) {
            console.error('PDF extraction error:', err);
            throw new Error(`Text extraction failed: ${err.message}`);
        }
    } else if (
        file.type === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ||
        file.name.endsWith('.docx')
    ) {
        try {
            const mammoth = require('mammoth');
            const result = await mammoth.extractRawText({ buffer });
            return result.value;
        } catch (err: any) {
            console.error('Docx extraction error:', err);
            throw new Error(`Docx extraction failed: ${err.message}`);
        }
    } else {
        return new TextDecoder().decode(arrayBuffer);
    }
}

/**
 * Generates a clean PDF of the Suitability Study analysis text.
 * The free report goes out as PDF (read-only). The purchased resume rewrite
 * uses a separate Word doc pipeline.
 */
export async function createGapPdf(analysis: string, companyName: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const chunks: Buffer[] = [];
        const doc = new PDFDocument({
            size: 'LETTER',
            margins: { top: 60, bottom: 60, left: 72, right: 72 },
            info: {
                Title: `Suitability Study — ${companyName}`,
                Author: 'SSLDUCK Career Services',
                Subject: 'Resume Gap Analysis & Suitability Study',
            },
        });

        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // ── Header ─────────────────────────────────────────────────────────
        doc.font('Helvetica-Bold')
           .fontSize(18)
           .fillColor('#1a1a2e')
           .text(`Suitability Study: ${companyName}`, { align: 'left' });

        doc.font('Helvetica')
           .fontSize(10)
           .fillColor('#666666')
           .text(`Generated by SSLDUCK Career Services · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'left' });

        doc.moveDown(0.5);
        doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor('#cccccc').stroke();
        doc.moveDown(1);

        // ── Body — parse markdown-lite ──────────────────────────────────────
        const lines = analysis.split('\n');

        for (const rawLine of lines) {
            const line = rawLine.trimEnd();

            if (line.startsWith('# ')) {
                doc.moveDown(0.8)
                   .font('Helvetica-Bold').fontSize(15).fillColor('#1a1a2e')
                   .text(line.replace(/^# /, ''), { continued: false });
                doc.moveDown(0.3);
            } else if (line.startsWith('## ')) {
                doc.moveDown(0.6)
                   .font('Helvetica-Bold').fontSize(13).fillColor('#003366')
                   .text(line.replace(/^## /, ''), { continued: false });
                doc.moveDown(0.3);
            } else if (line.startsWith('### ')) {
                doc.moveDown(0.4)
                   .font('Helvetica-Bold').fontSize(11).fillColor('#333333')
                   .text(line.replace(/^### /, ''), { continued: false });
                doc.moveDown(0.2);
            } else if (line.startsWith('---')) {
                doc.moveDown(0.4);
                doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor('#dddddd').stroke();
                doc.moveDown(0.4);
            } else if (line.trim() === '') {
                doc.moveDown(0.35);
            } else if (line.startsWith('| ')) {
                // Markdown table row — render as plain indented text
                const cells = line.split('|').map(c => c.trim()).filter(c => c && c !== '---' && !/^[-:]+$/.test(c));
                if (cells.length >= 2) {
                    const isHeader = line.includes('---|');
                    doc.font(isHeader ? 'Helvetica-Bold' : 'Helvetica')
                       .fontSize(9).fillColor('#111111')
                       .text(`  ${cells[0]}   →   ${cells[1]}`, { indent: 8 });
                } else if (cells.length === 1) {
                    doc.font('Helvetica').fontSize(9).fillColor('#111111')
                       .text(`  ${cells[0]}`, { indent: 8 });
                }
            } else {
                // Normal paragraph — handle inline **bold**
                const parts = line.split(/(\*\*.*?\*\*)/);
                if (parts.length === 1) {
                    doc.font('Helvetica').fontSize(10).fillColor('#111111').text(line, { continued: false });
                } else {
                    let started = false;
                    for (const part of parts) {
                        if (!part) continue;
                        if (part.startsWith('**') && part.endsWith('**')) {
                            doc.font('Helvetica-Bold').fontSize(10).fillColor('#111111')
                               .text(part.slice(2, -2), { continued: true });
                        } else {
                            doc.font('Helvetica').fontSize(10).fillColor('#111111')
                               .text(part, { continued: true });
                        }
                        started = true;
                    }
                    if (started) doc.text('', { continued: false }); // flush
                }
            }
        }

        // ── Footer ─────────────────────────────────────────────────────────
        doc.moveDown(2);
        doc.font('Helvetica').fontSize(9).fillColor('#999999')
           .text('Confidential · Prepared exclusively for the named recipient · sslduck.net', {
               align: 'center',
           });

        doc.end();
    });
}
