'use server';

import PDFDocument from 'pdfkit';

export async function extractTextFromFile(file: File): Promise<string> {
    console.log(`[GAP_UTILS] Extracting text from ${file.name} (${file.type})...`);
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    if (file.type === 'application/pdf') {
        try {
            const pdf = require('pdf-parse');
            const data = await pdf(buffer);
            return data.text;
        } catch (err: any) {
            console.error('PDF extraction error:', err);
            throw new Error(`Text extraction failed: ${err.message}`);
        }
    } else if (
        file.type === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ||
        file.name.endsWith('.docx')
    ) {
        try {
            const mammoth = require('mammoth');
            const result = await mammoth.extractRawText({ buffer });
            return result.value;
        } catch (err: any) {
            console.error('Docx extraction error:', err);
            throw new Error(`Docx extraction failed: ${err.message}`);
        }
    } else {
        return new TextDecoder().decode(arrayBuffer);
    }
}

/**
 * Generates a clean PDF of the Suitability Study analysis text.
 * The free report goes out as PDF (read-only). The purchased resume rewrite
 * uses a separate Word doc pipeline.
 */
export async function createGapPdf(analysis: string, companyName: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const chunks: Buffer[] = [];
        const doc = new PDFDocument({
            size: 'LETTER',
            margins: { top: 60, bottom: 60, left: 72, right: 72 },
            info: {
                Title: `Suitability Study — ${companyName}`,
                Author: 'SSLDUCK Career Services',
                Subject: 'Resume Gap Analysis & Suitability Study',
            },
        });

        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // ── Header ─────────────────────────────────────────────────────────
        doc.font('Helvetica-Bold')
           .fontSize(18)
           .fillColor('#1a1a2e')
           .text(`Suitability Study: ${companyName}`, { align: 'left' });

        doc.font('Helvetica')
           .fontSize(10)
           .fillColor('#666666')
           .text(`Generated by SSLDUCK Career Services · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'left' });

        doc.moveDown(0.5);
        doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor('#cccccc').stroke();
        doc.moveDown(1);

        // ── Body — parse markdown-lite ──────────────────────────────────────
        const lines = analysis.split('\n');
        let firstH2Seen = false;      // triggers page break after cover letter
        let skipChecklist = false;    // suppresses Best Practices Checklist section
        let consecutiveBlanks = 0;   // tracks runs of empty lines for spacing

        for (const rawLine of lines) {
            const line = rawLine.trimEnd();

            // ── Section skip: Best Practices Checklist ──────────────────────
            if (line.startsWith('## ') && line.includes('Best Practices Checklist')) {
                skipChecklist = true;
                continue;
            }
            if (skipChecklist) {
                // Resume rendering when the next ## heading appears
                if (line.startsWith('## ')) {
                    skipChecklist = false;
                    // fall through to render this heading
                } else {
                    continue;
                }
            }

            consecutiveBlanks = 0; // reset on every non-blank line

            if (line.startsWith('# ')) {
                doc.moveDown(0.8)
                   .font('Helvetica-Bold').fontSize(15).fillColor('#1a1a2e')
                   .text(line.replace(/^# /, ''), { continued: false });
                doc.moveDown(0.3);

            } else if (line.startsWith('## ')) {
                // Page break after cover letter — triggers on first ## heading
                if (!firstH2Seen) {
                    doc.addPage();
                    firstH2Seen = true;
                }

                let heading = line.replace(/^## /, '');

                // Rename Report 1 heading
                if (heading === 'Professional Profile') {
                    heading = 'Remarks From Glo';
                }

                // New page + title fix for Interview Questions
                if (heading.startsWith('Bonus: Probable Interview Questions')) {
                    doc.addPage();
                    heading = 'Bonus: Probable Interview Questions to Expect (Based on your Resume)';
                }

                doc.moveDown(0.6)
                   .font('Helvetica-Bold').fontSize(13).fillColor('#003366')
                   .text(heading, { continued: false });
                doc.moveDown(0.3);

            } else if (line.startsWith('### ')) {
                doc.moveDown(0.4)
                   .font('Helvetica-Bold').fontSize(11).fillColor('#333333')
                   .text(line.replace(/^### /, ''), { continued: false });
                doc.moveDown(0.2);

            } else if (line.startsWith('---')) {
                doc.moveDown(0.4);
                doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor('#dddddd').stroke();
                doc.moveDown(0.4);

            } else if (line.trim() === '') {
                consecutiveBlanks++;
                doc.moveDown(0.35); // each blank line adds 0.35; consecutive blanks stack
                continue;           // skip the reset below — next non-blank will reset

            } else if (line.startsWith('| ')) {
                // Markdown table row — render as plain indented text
                const cells = line.split('|').map(c => c.trim()).filter(c => c && c !== '---' && !/^[-:]+$/.test(c));
                if (cells.length >= 2) {
                    doc.font('Helvetica').fontSize(9).fillColor('#111111')
                       .text(`  ${cells[0]}   →   ${cells[1]}`, { indent: 8 });
                } else if (cells.length === 1) {
                    doc.font('Helvetica').fontSize(9).fillColor('#111111')
                       .text(`  ${cells[0]}`, { indent: 8 });
                }

            } else {
                // Normal paragraph — tokenize into bold / italic / URL / plain segments
                // Supports inline: **bold**, *italic*, https://url, plain text
                // Uses PDFKit continued:true chaining so all segments render on the same line.
                const tokenRegex = /(\*\*[^*]+?\*\*|\*[^*]+?\*|https?:\/\/[^\s]+)/g;
                const tokens: { text: string; type: 'bold' | 'italic' | 'url' | 'plain' }[] = [];
                let lastIndex = 0;
                let m: RegExpExecArray | null;
                while ((m = tokenRegex.exec(line)) !== null) {
                    if (m.index > lastIndex) {
                        tokens.push({ text: line.slice(lastIndex, m.index), type: 'plain' });
                    }
                    const raw = m[0];
                    if (raw.startsWith('**')) {
                        tokens.push({ text: raw.slice(2, -2), type: 'bold' });
                    } else if (raw.startsWith('*')) {
                        tokens.push({ text: raw.slice(1, -1), type: 'italic' });
                    } else {
                        tokens.push({ text: raw, type: 'url' });
                    }
                    lastIndex = m.index + raw.length;
                }
                if (lastIndex < line.length) {
                    tokens.push({ text: line.slice(lastIndex), type: 'plain' });
                }

                if (tokens.length === 0) {
                    // Nothing to render

                } else if (tokens.length === 1 && tokens[0].type === 'plain') {
                    // Pure plain text — single call, no overprint risk
                    doc.font('Helvetica').fontSize(10).fillColor('#111111')
                       .text(tokens[0].text, { continued: false });

                } else if (tokens.length === 1 && tokens[0].type === 'bold') {
                    // Entirely bold line (interview question headers)
                    doc.moveDown(0.35);
                    doc.font('Helvetica-Bold').fontSize(10).fillColor('#111111')
                       .text(tokens[0].text, { continued: false });
                    doc.moveDown(0.2);

                } else {
                    // Mixed — chain segments with continued:true, terminate last with continued:false
                    for (let i = 0; i < tokens.length; i++) {
                        const tok = tokens[i];
                        const isLast = i === tokens.length - 1;
                        const opts = { continued: !isLast };
                        if (tok.type === 'bold') {
                            doc.font('Helvetica-Bold').fontSize(10).fillColor('#111111')
                               .text(tok.text, opts);
                        } else if (tok.type === 'italic') {
                            doc.font('Helvetica-Oblique').fontSize(10).fillColor('#111111')
                               .text(tok.text, opts);
                        } else if (tok.type === 'url') {
                            doc.font('Helvetica').fontSize(10).fillColor('#1a56db')
                               .text(tok.text, { ...opts, link: tok.text, underline: true });
                            if (!isLast) doc.fillColor('#111111');
                        } else {
                            doc.font('Helvetica').fontSize(10).fillColor('#111111')
                               .text(tok.text, opts);
                        }
                    }
                    // Always reset font+color after a chained segment group
                    doc.font('Helvetica').fillColor('#111111');
                }
            }
        }

        // ── Footer ─────────────────────────────────────────────────────────
        doc.moveDown(2);
        doc.font('Helvetica').fontSize(9).fillColor('#999999')
           .text('Confidential · Prepared exclusively for the named recipient · sslduck.net', {
               align: 'center',
           });

        doc.end();
    });
}
