'use server';

import PDFDocument from 'pdfkit';

export async function extractTextFromFile(file: File): Promise<string> {
    console.log(`[GAP_UTILS] Extracting text from ${file.name} (${file.type})...`);
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    if (file.type === 'application/pdf') {
        try {
            const pdf = require('pdf-parse');
            const data = await pdf(buffer);
            return data.text;
        } catch (err: any) {
            console.error('PDF extraction error:', err);
            throw new Error(`Text extraction failed: ${err.message}`);
        }
    } else if (
        file.type === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ||
        file.name.endsWith('.docx')
    ) {
        try {
            const mammoth = require('mammoth');
            const result = await mammoth.extractRawText({ buffer });
            return result.value;
        } catch (err: any) {
            console.error('Docx extraction error:', err);
            throw new Error(`Docx extraction failed: ${err.message}`);
        }
    } else {
        return new TextDecoder().decode(arrayBuffer);
    }
}

/**
 * Generates a clean PDF of the Suitability Study analysis text.
 * The free report goes out as PDF (read-only). The purchased resume rewrite
 * uses a separate Word doc pipeline.
 */
export async function createGapPdf(analysis: string, companyName: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const chunks: Buffer[] = [];
        const doc = new PDFDocument({
            size: 'LETTER',
            margins: { top: 60, bottom: 60, left: 72, right: 72 },
            info: {
                Title: `Suitability Study — ${companyName}`,
                Author: 'SSLDUCK Career Services',
                Subject: 'Resume Gap Analysis & Suitability Study',
            },
        });

        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // ── Header ─────────────────────────────────────────────────────────
        doc.font('Helvetica-Bold')
           .fontSize(18)
           .fillColor('#1a1a2e')
           .text(`Suitability Study: ${companyName}`, { align: 'left' });

        doc.font('Helvetica')
           .fontSize(10)
           .fillColor('#666666')
           .text(`Generated by SSLDUCK Career Services · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'left' });

        doc.moveDown(0.5);
        doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor('#cccccc').stroke();
        doc.moveDown(1);

        // ── Body — parse markdown-lite ──────────────────────────────────────
        const lines = analysis.split('\n');
        let firstH2Seen = false;      // triggers page break after cover letter
        let skipChecklist = false;    // suppresses Best Practices Checklist section

        for (const rawLine of lines) {
            const line = rawLine.trimEnd();

            // ── Section skip: Best Practices Checklist ──────────────────────
            if (line.startsWith('## ') && line.includes('Best Practices Checklist')) {
                skipChecklist = true;
                continue;
            }
            if (skipChecklist) {
                // Resume rendering when the next ## heading appears
                if (line.startsWith('## ')) {
                    skipChecklist = false;
                    // fall through to render this heading
                } else {
                    continue;
                }
            }

            if (line.startsWith('# ')) {
                doc.moveDown(0.8)
                   .font('Helvetica-Bold').fontSize(15).fillColor('#1a1a2e')
                   .text(line.replace(/^# /, ''), { continued: false });
                doc.moveDown(0.3);

            } else if (line.startsWith('## ')) {
                // Page break after cover letter — triggers on first ## heading
                if (!firstH2Seen) {
                    doc.addPage();
                    firstH2Seen = true;
                }

                let heading = line.replace(/^## /, '');

                // Rename Report 1 heading
                if (heading === 'Professional Profile') {
                    heading = 'Remarks From Glo';
                }

                // New page + title fix for Interview Questions
                if (heading.startsWith('Bonus: Probable Interview Questions')) {
                    doc.addPage();
                    heading = 'Bonus: Probable Interview Questions to Expect (Based on your Resume)';
                }

                doc.moveDown(0.6)
                   .font('Helvetica-Bold').fontSize(13).fillColor('#003366')
                   .text(heading, { continued: false });
                doc.moveDown(0.3);

            } else if (line.startsWith('### ')) {
                doc.moveDown(0.4)
                   .font('Helvetica-Bold').fontSize(11).fillColor('#333333')
                   .text(line.replace(/^### /, ''), { continued: false });
                doc.moveDown(0.2);

            } else if (line.startsWith('---')) {
                doc.moveDown(0.4);
                doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor('#dddddd').stroke();
                doc.moveDown(0.4);

            } else if (line.trim() === '') {
                doc.moveDown(0.35);

            } else if (line.startsWith('| ')) {
                // Markdown table row — render as plain indented text
                const cells = line.split('|').map(c => c.trim()).filter(c => c && c !== '---' && !/^[-:]+$/.test(c));
                if (cells.length >= 2) {
                    doc.font('Helvetica').fontSize(9).fillColor('#111111')
                       .text(`  ${cells[0]}   →   ${cells[1]}`, { indent: 8 });
                } else if (cells.length === 1) {
                    doc.font('Helvetica').fontSize(9).fillColor('#111111')
                       .text(`  ${cells[0]}`, { indent: 8 });
                }

            } else {
                // Normal paragraph — handle inline **bold**
                const parts = line.split(/(\*\*.*?\*\*)/);

                if (parts.length === 1) {
                    // Check if line contains a URL — render as clickable hyperlink
                    const urlMatch = line.match(/(https?:\/\/[^\s]+)/);
                    if (urlMatch) {
                        const url = urlMatch[1];
                        const labelText = line.replace(url, '').trim();
                        if (labelText) {
                            doc.font('Helvetica').fontSize(10).fillColor('#111111')
                               .text(labelText + ' ', { continued: true });
                        }
                        doc.font('Helvetica').fontSize(10).fillColor('#1a56db')
                           .text(url, { link: url, underline: true, continued: false });
                        doc.fillColor('#111111');
                    } else {
                        // Pure plain text
                        doc.font('Helvetica').fontSize(10).fillColor('#111111')
                           .text(line, { continued: false });
                    }

                } else if (
                    line.startsWith('**') &&
                    line.endsWith('**') &&
                    line.split('**').length === 3
                ) {
                    // Entirely bold line (interview question headers, etc.)
                    // Use continued:false — guaranteed Y advance, no overprint
                    doc.moveDown(0.35);
                    doc.font('Helvetica-Bold').fontSize(10).fillColor('#111111')
                       .text(line.slice(2, -2), { continued: false });
                    doc.moveDown(0.2);

                } else {
                    // Mixed bold + plain: strip bold markers to avoid PDFKit
                    // continued:true wrapping bugs that cause line overprints
                    const stripped = line.replace(/\*\*(.*?)\*\*/g, '$1');
                    doc.font('Helvetica').fontSize(10).fillColor('#111111')
                       .text(stripped, { continued: false });
                }
            }
        }

        // ── Footer ─────────────────────────────────────────────────────────
        doc.moveDown(2);
        doc.font('Helvetica').fontSize(9).fillColor('#999999')
           .text('Confidential · Prepared exclusively for the named recipient · sslduck.net', {
               align: 'center',
           });

        doc.end();
    });
}
